# Metadata: nombre y sitemap
METADATA_URLS={
    'https://www.elcomercio.es/': {'nombre': 'El Comercio'},
    'https://www.lne.es/': {'nombre': 'La Nueva España'},
    'https://www.lavanguardia.com/': {'nombre': 'La Vanguardia',
                              'sitemap': ['sitemap-google-news.xml',
                                          'sitemap-news-agencias.xml'] +
                              [f'sitemap-news-agencias-{i}.xml' for i in range(1, 10)]},
    'https://www.larazon.es/': {'nombre': 'La Razón'},
    'https://www.rtpa.es/': {'nombre': 'Radiotelevisión del Principado de Asturias (RTPA)',
                              'sitemap': 'sitemap-noticias.xml'},
    'https://www.europapress.es/': {'nombre': 'Europa Press'},
    'https://www.20minutos.es/': {'nombre': '20 Minutos',
                                  'sitemap': 'sitemap-google-news.xml'},
    'https://www.elperiodico.com/' : {'nombre': 'El Periódico',
                                      'sitemap': 'google-news.xml'},
    'https://www.eldiario.es/' : {'nombre': 'ElDiario.es'},
    'https://www.elconfidencial.com/': {'nombre': 'El Confidencial',
                                        'sitemap': 'newsitemap_4.xml'},
    'https://www.culturalgijonesa.org/': {'nombre': 'Cultural Gijonesa'},
    'https://www.elespanol.com/' : {'nombre': 'El Español',
                                    'sitemap': 'sitemap_google_news.xml'},
    'https://www.nortes.me/': {'nombre': 'Nortes'},
    'https://www.tribunasalamanca.com/': {'nombre': 'Tribuna Salamanca'},
    'https://migijon.com/': {'nombre': 'Mi Gijón'},
    'https://www.infobae.com/' : {'nombre': 'Infobae',
                                  'sitemap': 'arc/outboundfeeds/news-sitemap2/'},
    'https://www.telecinco.es/' : {'nombre': 'Telecinco'},
    'https://www.laprovincia.es/' : {'nombre': 'La Provincia'},
    'https://www.laopiniondemalaga.es/': {'nombre': 'La Opinión de Málaga'},
    'https://www.elfielato.es/': {'nombre': 'El Fielato y El Nora'},
    'https://www.teleprensa.com/': {'nombre': 'Teleprensa'},
    'https://forbes.es/': {'nombre': 'Forbes'},
    'https://itg.es/': {'nombre': 'ITG centro tecnológico'},
    'https://www.eldia.es/': {'nombre': 'El Dia'},
    'https://www.nationalgeographic.es/': {'nombre': 'Historia National Geographic'},
    'https://iymagazine.es/': {'nombre': 'IyMagazine'},
    'https://www.lacerca.com/': {'nombre': 'La Cerca'},
    'https://www.tribunaavila.com/': {'nombre': 'Tribuna de Ávila'},
    'https://www.latribunadealbacete.es/': {'nombre': 'La Tribuna de Albacete'},
    'https://www.eldiariomontanes.es/': {'nombre': 'El Diario Montañés'},
    "https://www.larioja.com/":{"nombre": "La Rioja"},
    "https://www.almerianoticias.es/":{"nombre": "Almería Noticias"},
    "https://news.ual.es/":{"nombre": "UALNEWS"},
    "https://www.farodevigo.es/":{"nombre": "Faro de Vigo"},
    "https://www.diariocordoba.com/": {'nombre': 'Diario Córdoba'},
    "https://www.diariodeibiza.es/": {'nombre': 'Diario de Ibiza'},
    "https://segoviaudaz.es/": {'nombre': 'SegoviAudaz'},
    'https://www.noticiasde.es/': {'nombre': 'NoticiasDe'},
    'https://www.redaccionmedica.com/': {'nombre': 'Redacción Médica'},
    'https://cronicadeandalucia.com/': {'nombre': 'Crónica de Andalucía'},
    'https://www.diariodevalderrueda.es/': {'nombre': 'Diario de Valderrueda'},
    'https://galiciadigital24horas.com/': {'nombre': 'Galicia Digital 24 Horas'},
    'https://www.laescena.es/': {'nombre': 'La Escena'},
    'https://valencia24horas.com/': {'nombre': 'Valencia 24 Horas'},
    'https://www.eleconomista.es/': {'nombre': 'El Economista'},
    'https://www.ondacero.es/': {'nombre': 'Onda Cero'},
    'https://www.laopinioncoruna.es/': {'nombre': 'La Opinión A Coruña'},
    'https://economia3.com/': {'nombre': 'Economía 3'},
    'https://inmediaciones.org/': {'nombre': 'Inmediaciones' },
    'https://www.sport.es/': {'nombre': 'Sport'},
    'https://ort-ort.com/': {'nombre': 'ORT Noticias del Occidente de Asturias'},
    'https://ethic.es/': {'nombre': 'Ethic'},
    'https://www.tribunaavila.com/': {'nombre': 'Tribuna Ávila'},
    'https://www.laopiniondezamora.es/': {'nombre': 'La Opinión de Zamora'},
    'https://www.elcorreogallego.es/': {'nombre': 'El Correo Gallego'},
    'https://www.informacion.es/': {'nombre': 'INFORMACIÓN'},
    'https://www.elperiodicoextremadura.com/': {'nombre': 'El Periódico Extremadura'},
    'https://www.laopiniondemurcia.es/': {'nombre': 'La Opinión de Murcia'},
    'https://www.levante-emv.com/': {'nombre': 'Levante-EMV' },
    'https://www.diariodemallorca.es/': {'nombre': 'Diario de Mallorca'},
    'https://www.elperiodicodearagon.com/': {'nombre': 'El Periódico de Aragón'},
    'https://www.latribunadealbacete.es/': {'nombre': 'La Tribuna de Albacete'},
    'https://www.diariosur.es/': {'nombre': 'Diario Sur'},
    'https://www.malagahoy.es/': {'nombre': 'Málaga Hoy'},
    'https://www.superdeporte.es/': {'nombre': 'Superdeporte'},
    'https://www.elperiodicomediterraneo.com/': {'nombre': 'El Periódico Mediterráneo'},
    'https://www.salamanca24horas.com/': {'nombre': 'Salamanca 24 Horas' },
    'https://www.lacerca.com/': {'nombre': 'La Cerca'},
    'https://deportesmenorca.com/': {'nombre': 'Deportes Menorca'},
    'https://menorcaaldia.com/': {'nombre': 'Menorca al Día'},
    'https://www.lanzadigital.com/': {'nombre': 'Lanza Digital'},
    'https://www.menorca.info/': {'nombre': 'MENORCA'},
    'https://www.lacomarcadepuertollano.com/': {'nombre': 'La Comarca de Puerto Llano'},
    'https://www.gciencia.com/': {'nombre': 'GCiencia'},
    'https://www.eldebate.com/': {'nombre': 'El Debate', 'sitemap': 'sitemap-index.xml' },
    'https://www.magisnet.com/': {'nombre': 'Magisnet', 'sitemap': 'sitemap_index.xml'},
    'https://www.corresponsables.com/': {'nombre': 'Corresponsables',
                                          'sitemap': [f'post-sitemap{i}.xml' for i in range(30, 50)]},
    'https://www.diariodepontevedra.es/': {'nombre': 'Diario de Pontevedra'},
    'https://www.infoclm.es/': {'nombre': 'Periódico digital de Castilla-La Mancha'},
    'https://mariskalrock.com/': {'nombre': 'MariskalRock'},
    'https://salamancartvaldia.es/': {'nombre': 'Salamanca al Día'},
            'https://diariofarma.com/': {'nombre': 'Diario Farma'},
    'https://valenciaplaza.com/': {'nombre': 'Valencia Plaza'},
    'https://www.mundiario.com/': {'nombre': 'Mundiario'},
    'https://www.farmaventas.es/': {'nombre': 'Farmaventas',
                                    'sitemap': 'sitemap.xml'},
    'https://elportaluco.com/': {'nombre': 'El Portaluco'},
            'https://entomelloso.com/': {'nombre': 'Tomelloso'},
    'https://www.granadadigital.es/': {'nombre': 'Granada Digital',
                                        'sitemap': 'sitemap_index.xml'},
    'https://www.lavozdegalicia.es/': {'nombre': 'La Voz de Galicia'},
    'https://www.asturiasmundial.com/': {'nombre': 'Asturias Mundial'},
    'https://www.lagacetadesalamanca.es/': {'nombre': 'La Gaceta de Salamanca'},
    'https://noticias.juridicas.com/': {'nombre': 'Noticias Jurídicas'},
    'https://fernandezrozas.com/': {'nombre': 'Blog de José Carlos Fernández Rozas',
                                    'sitemap': 'news-sitemap.xml'},
    'https://www.vozpopuli.com/': {'nombre': 'Voz Populi'},
    'https://www.diariodelpuerto.com/': {'nombre': 'Diario del Puerto'},
    'https://www.abc.es/': {'nombre': 'ABC'}, #newspaper
    'https://www.lavozdeasturias.es/': {'nombre': 'La Voz de Asturias'},
    'https://cualia.es/': {'nombre': 'Cualia'},
    'http://www.gentedigital.es/' : {'nombre': 'Gente Digital'},
    'https://www.8directo.com/':{'nombre': '8directo'},
    'https://www.lanuevacronica.com/': {'nombre': 'La Nueva Crónica'},
    'https://elpais.com/': {'nombre': 'El Pais'},
    'https://www.elperiodicodecanarias.es/': {'nombre': 'El Periodico de Canarias'},
    'https://www.immedicohospitalario.es/': {'nombre': 'IM Médico'},
    'https://bilbao24horas.com/': {'nombre': 'Bilbao 24 Horas'},
    'https://www.diariodeleon.es/': {'nombre': 'Diario de León'},
    'https://cronicaeconomica.com/': {'nombre': 'Crónica Económica'},
    'https://ahoraleon.com/': {'nombre': 'Ahora León'},
    "https://www.feb.es/": {'nombre': 'Federación Española de Baloncesto'},
    'https://www.consalud.es/': {'nombre': 'ConSalud'},
    'https://www.rrhhdigital.com/': {'nombre': 'RRHH Digital'},
    'https://www.diariomedico.com/': {'nombre': 'Diario Médico'},
    'https://vivirediciones.es/': {'nombre': 'Vivir Ediciones'},
    'https://www.granadahoy.com/': {'nombre': 'Granada Hoy'},
    'https://www.espormadrid.es/': {'nombre': 'Es por madrid'},
    'https://www.granadaesnoticia.com/': {'nombre': 'Granada es noticia'},
    'https://novaciencia.es/': {'nombre': 'Nova Ciencia'},
    'https://www.industriaquimica.es/': {'nombre': 'Industria Química'},
    'https://www.bolsamania.com/': {'nombre': 'Bolsamania',
                                    'sitemap': 'sitemap.xml'},
    'https://www.rutapesquera.com/': {'nombre': 'Ruta Pesquera'},
    'https://www.santanderdigital24horas.com/': {'nombre': 'Santander Digital 24 Horas'},
    'https://isanidad.com/': {'nombre': 'iSanidad'},
    'https://www.vocesdecuenca.com/': {'nombre': 'Voces de Cuenca'}
}
